### ISSUE TITLE
Script update_password_in_csv.py doesn't work

### ISSUE THREAD

**Issue by bkaczynski** [iredmail/iRedAdmin#14]
Any ideas why this script doesn't work?

```
# python3 update_password_in_csv.py passwords.csv
Traceback (most recent call last):
  File "update_password_in_csv.py", line 37, in <module>
    from tools.ira_tool_lib import debug, logger, get_db_conn
  File "/opt/iRedAPD-3.0/tools/../tools/__init__.py", line 71
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

```
# python3 -V
Python 3.6.8
# pip3 -V
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
```

**Comment by iredmail** [comment]
You're running iRedAPD-3.0, it's a Python-2 script, not Python-3.
